# Use an official Node.js runtime as the base image
FROM node:18-slim

# Set the working directory inside the container
WORKDIR /usr/src
RUN git clone https://github.com/esemwy/rpg-docs.git app
WORKDIR /usr/src/app
RUN npm install
# Set the port that the app will run on
EXPOSE 3000

# Define the command to run the application
CMD ["npm", "start"]

