services:
  docs-server:
    image: docs-server:latest
    container_name: docs-server
    build:
      context: .
      dockerfile: Dockerfile.docs
    volumes:
      - ./pdf:/usr/src/app/pdf:ro
      - ./coverpages:/usr/src/app/coverpages:ro
      - ./metadata.json:/usr/src/app/metadata.json:ro
    restart: unless-stopped